### ISSUE TITLE
update bundled p2pool to v4.2

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#35]
**Feature request**
update bundled p2pool to newest version(currently newest version is v4.2)

**Additional context**
[V4.2](https://github.com/SChernykh/p2pool/releases/tag/v4.2)

**Comment by Cyrix126** [comment]
Oh I checked the same day as the release but didn't check just before doing it.
I will make a script for the release tools to check the newest version of included binairies and ask for confirmation if different than current ones. 
I will not include newest versions automatically because of https://github.com/Cyrix126/gupaxx/issues/4

**Comment by Cyrix126** [comment]
fixed in https://github.com/Cyrix126/gupaxx/commit/f6dc8d463d61a40cf9c7b9ddaa6dc8a18da57c11
Will put a release shortly.

**Comment by Cyrix126** [comment]
closed by https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.3
