### ISSUE TITLE
P2pool status shows green even after Node is killed

### ISSUE THREAD

**Issue by sceniclife** [Cyrix126/gupaxx#57]
## OS & Version:
Windows 10, Gupaxx v1.6.0

## Bug
P2pool status shows green 'ok' status after Node is killed

## Steps
1. Start Node
2. Start P2pool
3. Wait for both to show green 'ok' status
4. Kill Node
5. P2pool will report ZMQ communication error but will stay green status.

## Additional Info
If P2pool is started first and Node is never started or connected, P2pool status shows orange state. I would expect this be the state that P2pool reports if Node was killed while running.

**Comment by Cyrix126** [comment]
Gupaxx could watch the console output of p2pool to know when to set state to orange instead green. But if the user set the log level to 0, it would not work since there would be no error messages. Gupaxx can't watch the status of Node for that since P2Pool could connect to a non local Node. Also to know if the connection is restored after a failure, P2Pool would need to be set to log level 2. 
The first solution would be to force the minimum log level to 2 or to get the status from the API, which for now does not include it. I don't know C++, so I can't make a PR for it.
https://github.com/SChernykh/p2pool/issues/328
